### ISSUE TITLE
example to query nodes based on locations or capacity

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/info_specs_grid3#10]

**Comment by RafyAmgadBenjamin** [comment]
Query nodes based on location, city, and country is done

PR
https://github.com/threefoldtech/vgrid/pull/15

**Comment by RafyAmgadBenjamin** [comment]
Query nodes based on capacity `sru,hru,mru` and `cru` is done

PR
https://github.com/threefoldtech/vgrid/pull/24

**Comment by xmonader** [comment]
And added to wiki here 0e202324472e03db4858a1a84b949502e15d22c5
