### ISSUE TITLE
initial setup, get documentation in WIKI

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/info_specs_grid3#13]
- [x] ygg 0.4 and add some ipv4 peers https://publicpeers.neilalexander.dev
- [x] open port 8051 for rmb https://github.com/threefoldtech/rmb
- [x] use https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fexplorer.devnet.grid.tf%2Fws#/explorer create account -ed25519- , add funds using alice 
![image](https://user-images.githubusercontent.com/64129/125321199-bc340200-e33c-11eb-80c9-d37f4c843f28.png)
- [x] add types https://github.com/threefoldtech/tfgrid-api-client/blob/master/types.json in developer settings 
![image](https://user-images.githubusercontent.com/64129/125321714-441a0c00-e33d-11eb-8546-09704d5ceffd.png)
- [x] create twin
- [x] visit github.com/threefoldtech/rmb, check  https://github.com/threefoldfoundation/info_digitaltwin/blob/fd8060c68ed92ddd8ee94a3a24e43b5438fb5fac/src/development/architecture/architecture_rmb.md#example-getting-stellar-wallet-balance

**Comment by despiegk** [comment]
DOCUMENT ALL OF THIS IN WIKI
THEN CLOSE THIS

**Comment by xmonader** [comment]
https://github.com/threefoldtech/TFGRID/blob/development/wiki/tfgrid_substrate/substrate/grid_substrate_getting_started.md
