### ISSUE TITLE
prepare gitpod in this repo

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/info_specs_grid3#14]
# requirements

- [x] should have v 
- [ ] should have node installed
- [x] should have redis
- [x] should have rmb
- [ ] get twin_server repo over git
- [ ] check all code in nice modules in right location of twin_server repo
- [ ] should have twin-server running
- [ ] run test script in v which calls the twin-server ping service over RMB
- [ ] run test script in v which calls the twin-server stellar client service over RMB with minimal test

**Comment by hossnys** [comment]
done here a7013dc &  0dc7a29


![Screenshot from 2021-07-15 17-02-47](https://user-images.githubusercontent.com/26298009/125810708-5fe7fca6-a074-4118-80ca-cab283e346ea.png)
