### ISSUE TITLE
Some questions on the  SmartContract specs

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/info_specs_grid3#18]
/src/specs/substrate/smartContract/contract.md

Questions:
- [ ] why is the node address  in the contract an ss58 address and where does this come from? /src/specs/substrate/griddb/griddb.md does not mention the assignment of ss58 addresses.
- [x] Can we create a full definition of all fields inside a contract?
- [ ] The contract explanation states an optional data field with the deployment data being encrypted with the user's public key, How does the node gets the deployment data ? I assume the deployment is present again in the contract encrypted with the node's public key.
- [x] which keys are used to encrypt the data? In the griddb ER Diagram public keys are not mentioned.

Remarks:
- [x] in the json contract example the fields are `address` and `ips` while in the explanation `node_address` and `public_ips` is used.

**Comment by DylanVerstraete** [comment]
> * [ ]  why is the node address  in the contract an ss58 address and where does this come from? /src/specs/substrate/griddb/griddb.md does not mention the assignment of ss58 addresses.

SS58 is the default encoding for substrate ed25519 and sr25519 addreses. We just use this format on chain to make validation easier.

**Comment by DylanVerstraete** [comment]
> The contract explanation states an optional data field with the deployment data being encrypted with the user's public key, How does the node gets the deployment data ? I assume the deployment is present again in the contract encrypted with the node's public key.

This data field is optionally filled in by the user. The deployment is communicated over RMB to the node, the node does not read this field from the contract to deploy the workload

**Comment by DylanVerstraete** [comment]
>  which keys are used to encrypt the data? In the griddb ER Diagram public keys are not mentioned.

Can be of the user/client choice

**Comment by DylanVerstraete** [comment]
>  Can we create a full definition of all fields inside a contract?

I updated the type in the spec

>  in the json contract example the fields are address and ips while in the explanation node_address and public_ips is used.

resolved

**Comment by robvanmieghem** [comment]
> > * [ ]   why is the node address  in the contract an ss58 address and where does this come from? /src/specs/substrate/griddb/griddb.md does not mention the assignment of ss58 addresses.
> 
> SS58 is the default encoding for substrate ed25519 and sr25519 addreses. We just use this format on chain to make validation easier.

I know what SS58 is but my question is where the address comes from, It is not mentioned in /src/specs/substrate/griddb/griddb.md

**Comment by robvanmieghem** [comment]
> > The contract explanation states an optional data field with the deployment data being encrypted with the user's public key, How does the node gets the deployment data ? I assume the deployment is present again in the contract encrypted with the node's public key.
> 
> This data field is optionally filled in by the user. The workload is communicated over RMB to the node, the node does not read this field from the contract to deploy the workload


This is in contradiction of what is stated in /src/specs/substrate/smartContract/contract.md:
The flow diagram indicates that only the contract id is sent to the node and also the explanation below says so:
"The Node reads from the RMB and sees a deploy command, it reads the contractID and fetches that Contract from this pallet's storage. It decodes the workload and does validation before it deploys the contents"

**Comment by DylanVerstraete** [comment]
> The flow diagram indicates that only the contract id is sent to the node and also the explanation below says so:
> "The Node reads from the RMB and sees a deploy command, it reads the contractID and fetches that Contract from this pallet's storage. It decodes the workload and does validation before it deploys the contents"

Ah right, than the flow diagram is incorrect. This was first understood from the initial specs but was changed after. I'll correct it, sorry!

**Comment by DylanVerstraete** [comment]
@robvanmieghem flow diagram updated

**Comment by robvanmieghem** [comment]
> @robvanmieghem flow diagram updated

Can you also correct the text explanation?
