### ISSUE TITLE
docu how to use TFGrid explorer + test scripts

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/info_specs_grid3#21]
see vgrid/tfgriddb/explorer.v
see info_tfchain/tfgrid_explorer dir

need many more examples

also how to use the GRAPHQL language, how does it work

also how can they access the GRAPHQL interface, is the interface ready to be used

specify some example queries

**Comment by despiegk** [comment]
add to wiki in vgrid

**Comment by xmonader** [comment]
how about this one? 0e202324472e03db4858a1a84b949502e15d22c5
